### ISSUE TITLE
Adding prices by hour

### ISSUE THREAD

**Issue by angoyd** [Danielhiversen/pyTibber#94]
Any chance of adding the prices of today and to tomorrow to the sensor in HomeAssistant, today I´m fetching them via an rest sensor, and then displaying them in an custom Lovelace chart card.

The Restsensor set up looks like this today

``` yaml
 - platform: rest
    name: Tibber Price
    resource: https://api.tibber.com/v1-beta/gql
    method: POST
    payload: '{ "query": "{viewer {homes {currentSubscription {priceInfo {today {total} tomorrow {total}}}}}}"}'
    headers:
      Authorization: "Bearer <token>"
      User-Agent: Home Assistant
      Content-Type: application/json
    json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
    json_attributes:
      - today
      - tomorrow
    scan_interval: 14400
    value_template: 'OK'
```
And then I display it in my custom lovelace card found here [https://github.com/angoyd/hass-things/tree/main/tibber-card](url).

But it would have been nice not to have to setup an extra rest sensor to get the prices over the day, also its and extra call for the tibber api.
